- path: hts_codes_categories_bolstered_final.csv
- path: allied_comtrade_energy_data.csv
  optional: yes
- path: imf_dip.csv
- path: OneDrive - RMI/New Energy Industrial Strategy - Documents/Research/Data/scatter_index.csv
  optional: yes
- path: OneDrive - RMI/New Energy Industrial Strategy - Documents/NEIS Center Asia
    Trips/Research/Benchmark_Indices.xlsx
- path: ei_stat_review_world_energy.csv
- path: 2024-10-29 - New Energy Outlook 2024.csv
- path: iea_criticalminerals_25.csv
- path: yao_etal_nature_supplychains.xlsx
- path: ei_stat_review_world_energy_wide.xlsx
- path: MCS2025_World_Data.csv
- path: iea_cleantech_Midstream.csv
- path: ev_Midstream_capacity.csv
- path: greenplexity_scrape_full.csv
- path: hs92_country_product_year_4.csv
- path: hs92_country_product_year_6.csv
- path: Columbia University Critical Minerals Dashboard/unique_comtrade.csv
- path: 2025-03-24 - 2025 LCOE Data Viewer Tool.csv
- path: bis_debtserviceratio.csv
- path: imf_lending_rates.csv
- path: imf_ppi.csv
- path: wipo_treated_indicator_trends_2025.csv
- path: BNEF_Energy Transition Supply Chains 2025.xlsx
- path: 2025-06-03 - Energy Transition Investment Trends 2025 Countries Annex.xlsx
- path: Relative_Costs_IEA.csv
- path: WEO2024_AnnexA_Free_Dataset_World.csv
- path: IEA_EVDataExplorer2025.xlsx
- path: Market Size for Technology and Supply Chain.xlsx
- path: clean_energy_foreign_policy_heatmap.xlsx
- path: ipcc_ghg_intensity.csv
- path: CAT_country ratings data.csv
- path: wb_doingbusiness.csv
- path: wb_wdi.csv
- path: oecd_1215.csv
- path: oecd_1518.csv
- path: oecd_1823.csv
- path: clean_industry_naics_test.xlsx
- path: egrid2023_data_metric_rev2.xlsx
- path: 2022-NEI-Co-pollutant data.xlsx
- path: 2022-NEI-Co-pollutant-data-onroad.xlsx
- path: 2020 Facility-Level Data for Point  Emissions (70f61977-e493-46d2-b03d-b62a6e683153).xlsx
- path: ghg_ems_fossil_combustion_fuel.csv
- path: us_outbound_15_24.csv
- path: fossil_industry_naics.xlsx
- path: OneDrive - RMI/Documents - US Program/6_Projects/Clean Regional Economic Development/ACRE/Data/Raw
    Data/hts_codes_categories.csv
- path: OneDrive - RMI/Documents - US Program/6_Projects/Clean Regional Economic Development/ACRE/Data/Raw
    Data/clean_investment_monitor_q4_2024/quarterly_actual_investment.csv
- path: battery_hscodes_mit.csv
